import { createElement } from "react";

export interface ImageProps {
  /** Source path — relative to `/public` or an absolute URL. */
  src: string;
  alt: string;
  /** Intrinsic width in pixels. Used to generate the srcset breakpoints. */
  width: number;
  /** Intrinsic height in pixels. Used to preserve layout before load. */
  height: number;
  /**
   * The `sizes` attribute passed to the `<img>` element.
   * @example "(max-width: 768px) 100vw, 50vw"
   */
  sizes?: string | undefined;
  /**
   * Mark the image as the LCP element. Sets `loading="eager"` and
   * `fetchpriority="high"` — omit the blur-up placeholder to avoid CLS.
   */
  priority?: boolean | undefined;
  /** Additional class names. */
  className?: string | undefined;
  /** Quality 1–100. Defaults to 80. */
  quality?: number | undefined;
  /**
   * Base64-encoded tiny placeholder generated by `generateBlurPlaceholder()`.
   * When provided, the image fades in over the blurred placeholder for an
   * instant-load feel without layout shift.
   */
  blurDataURL?: string | undefined;
}

// Standard responsive breakpoints (matches Tailwind + common viewport widths).
const BREAKPOINTS = [320, 640, 750, 828, 1080, 1200, 1920];

/**
 * Rust-powered optimised image component.
 *
 * - Generates a `srcset` of WebP variants via `/_alab/image` (Rust napi).
 * - Blur-up placeholder support: pass `blurDataURL` from `generateBlurPlaceholder()`.
 * - `loading="lazy"` by default; use `priority` for LCP images.
 * - Always sets `width` + `height` to eliminate CLS (Cumulative Layout Shift).
 *
 * @example
 * ```tsx
 * import { Image, generateBlurPlaceholder } from "alab/components";
 *
 * // In a server function — runs on the server at build/request time:
 * const blur = await generateBlurPlaceholder("/hero.jpg");
 *
 * // In the page component:
 * <Image src="/hero.jpg" alt="Hero" width={1200} height={600} priority blurDataURL={blur} />
 * ```
 */
export function Image({
  src,
  alt,
  width,
  height,
  sizes,
  priority = false,
  className,
  quality = 80,
  blurDataURL,
}: ImageProps) {
  const q = Math.max(1, Math.min(100, quality));
  const encodedSrc = encodeURIComponent(src);

  // Build srcset: breakpoints ≤ intrinsic width + the intrinsic width itself.
  const widths = Array.from(
    new Set([...BREAKPOINTS.filter((w) => w < width), width]),
  ).sort((a, b) => a - b);

  const srcset = widths
    .map((w) => `/_alab/image?src=${encodedSrc}&w=${w}&q=${q}&fmt=webp ${w}w`)
    .join(", ");

  const defaultSrc = `/_alab/image?src=${encodedSrc}&w=${width}&q=${q}&fmt=webp`;

  const style: Record<string, string> = {
    maxWidth: "100%",
    height: "auto",
  };

  // Blur-up: show the tiny placeholder as a CSS background while the real image loads.
  if (blurDataURL && !priority) {
    style["backgroundImage"] = `url(${blurDataURL})`;
    style["backgroundSize"] = "cover";
    style["backgroundPosition"] = "center";
  }

  return createElement("img", {
    src: defaultSrc,
    srcSet: srcset,
    sizes: sizes ?? `${width}px`,
    alt,
    width,
    height,
    loading: priority ? "eager" : "lazy",
    fetchPriority: priority ? "high" : undefined,
    decoding: "async",
    className,
    style,
  });
}

/**
 * Generate a Base64 blur-up placeholder for an image in `public/`.
 *
 * Calls the Rust napi binding to resize the image to 8px wide and encode it
 * as a tiny WebP, then Base64-encodes it into a data URL ready for `blurDataURL`.
 *
 * Run this in a server function — it reads from disk and must not run in the browser.
 *
 * @param src - Path relative to `public/` (e.g. `"/hero.jpg"`)
 * @param publicDir - Absolute path to the `public/` directory
 */
export async function generateBlurPlaceholder(
  src: string,
  publicDir: string,
): Promise<string> {
  const { readFile } = await import("node:fs/promises");
  const { resolve } = await import("node:path");

  const safeSrc = src.replace(/\.\./g, "").replace(/^\/+/, "");
  const filePath = resolve(publicDir, safeSrc);

  const input = await readFile(filePath);

  let napi: { optimizeImage: (b: Buffer, q: number | null, w: number | null, h: null, fmt: string) => Promise<Buffer> };
  try {
    napi = (await import("@alab/compiler")) as typeof napi;
  } catch {
    // napi not built — return empty string (image still loads, just no blur effect)
    return "";
  }

  const tiny = await napi.optimizeImage(input, 40, 8, null, "webp");
  const b64 = Buffer.from(tiny).toString("base64");
  return `data:image/webp;base64,${b64}`;
}
