/**
 * `alab test` — zero-config test runner.
 *
 * Runs Vitest with the correct environment pre-configured for Alab apps:
 * - SSR modules tested in `node` environment (React server rendering)
 * - Client modules tested in `jsdom` environment (React DOM)
 * - Alab's Vite plugin wired in so `.server.ts` boundary rules apply
 * - `alab/test` utilities (`mockServerFn`, `renderPage`) available globally
 *
 * Usage:
 *   alab test              — run all tests once
 *   alab test --watch      — watch mode
 *   alab test --ui         — Vitest UI
 *   alab test src/foo.test.ts  — run specific file(s)
 */

import { spawn } from "node:child_process";
import { resolve } from "node:path";
import { existsSync, writeFileSync } from "node:fs";

interface TestOptions {
  cwd: string;
  watch?: boolean;
  ui?: boolean;
  files?: string[];
}

/**
 * Generate a `vitest.config.ts` in the project root if one doesn't exist.
 * This is written to a temp path and passed via `--config` so it doesn't
 * overwrite an existing user config.
 */
function generateVitestConfig(cwd: string): string {
  const configPath = resolve(cwd, ".alabjs/vitest.config.ts");
  const config = `// Auto-generated by \`alab test\` — do not edit manually.
// Customise by creating your own vitest.config.ts in the project root.
import { defineConfig } from "vitest/config";
import { alabPlugin } from "alabjs-vite-plugin";

export default defineConfig({
  plugins: [alabPlugin()],
  test: {
    globals: true,
    environment: "node",
    environmentMatchGlobs: [
      // Client-side component tests run in jsdom
      ["**/*.client.test.{ts,tsx}", "jsdom"],
      ["**/*.browser.test.{ts,tsx}", "jsdom"],
    ],
    setupFiles: [],
    include: ["**/*.{test,spec}.{ts,tsx}"],
    exclude: ["node_modules", ".alabjs"],
    coverage: {
      provider: "v8",
      reporter: ["text", "html"],
    },
  },
});
`;
  writeFileSync(configPath, config, "utf8");
  return configPath;
}

export async function test({ cwd, watch = false, ui = false, files = [] }: TestOptions) {
  // Ensure .alabjs/ exists
  const dotAlab = resolve(cwd, ".alabjs");
  if (!existsSync(dotAlab)) {
    const { mkdirSync } = await import("node:fs");
    mkdirSync(dotAlab, { recursive: true });
  }

  // Use the project's local vitest if available, otherwise fall back to npx.
  const vitestBin = resolve(cwd, "node_modules/.bin/vitest");
  const bin = existsSync(vitestBin) ? vitestBin : "npx";
  const binArgs = existsSync(vitestBin) ? [] : ["vitest"];

  // If the user already has a vitest config, respect it.
  const userConfig = ["vitest.config.ts", "vitest.config.js"].find((f) =>
    existsSync(resolve(cwd, f)),
  );

  const configPath = userConfig ? resolve(cwd, userConfig) : generateVitestConfig(cwd);

  const args: string[] = [
    ...binArgs,
    ...(ui ? ["--ui"] : []),
    ...(watch ? [] : ["run"]),
    "--config", configPath,
    ...files,
  ];

  console.log(`  alab  running tests${watch ? " (watch)" : ""}...\n`);

  await new Promise<void>((ok, fail) => {
    const child = spawn(bin, args, { cwd, stdio: "inherit", shell: true });
    child.on("close", (code) => {
      if (code === 0 || watch) ok();
      else fail(new Error(`[alabjs] Tests failed (vitest exited ${code})`));
    });
    child.on("error", fail);
  });
}
