/* eslint-disable */
// prettier-ignore
// Auto-generated by napi-rs — do not edit manually.
// Loads the correct platform-specific native binary.

const { existsSync } = require('fs')
const { join } = require('path')
const { platform, arch } = process

let nativeBinding = null
let loadError = null

function isMusl() {
  if (process.versions?.electron) return false
  // Check /proc/self/maps for musl
  try {
    return require('fs').readFileSync('/proc/self/maps', 'utf8').includes('musl')
  } catch {
    return false
  }
}

const targets = {
  win32: { x64: 'win32-x64-msvc' },
  darwin: { x64: 'darwin-x64', arm64: 'darwin-arm64' },
  linux: {
    x64: isMusl() ? 'linux-x64-musl' : 'linux-x64-gnu',
    arm64: isMusl() ? 'linux-arm64-musl' : 'linux-arm64-gnu',
  },
}

const target = targets[platform]?.[arch]

if (target) {
  const localFile = join(__dirname, `alab-napi.${target}.node`)

  if (existsSync(localFile)) {
    // Development: binary built locally via `cargo build`
    try {
      nativeBinding = require(localFile)
    } catch (e) {
      loadError = e
    }
  } else {
    // Production: load from the scoped platform package
    try {
      nativeBinding = require(`@alabjs/compiler-${target}`)
    } catch (e) {
      loadError = e
    }
  }
}

if (!nativeBinding) {
  const supported = Object.entries(targets)
    .flatMap(([os, archs]) => Object.values(archs).map((t) => `${os}-${t}`))
    .join(', ')

  throw new Error(
    `[alabjs] Failed to load the Rust compiler binary.\n` +
    `  Platform: ${platform}-${arch}\n` +
    `  Supported: ${supported}\n` +
    (loadError ? `  Error: ${loadError.message}\n` : '') +
    `\n` +
    `  To build locally: cargo build --release -p alab-napi\n` +
    `  Then copy: target/release/libalab_napi.dylib → crates/alab-napi/alab-napi.darwin-arm64.node`
  )
}

module.exports = nativeBinding
