import type { PageMetadata } from "../types/index.js";

export interface HtmlShellOptions {
  metadata: PageMetadata;
  /** Serialised params JSON string to embed in the page for client hydration. */
  paramsJson: string;
  /** Serialised search-params JSON string. */
  searchParamsJson: string;
  /** Relative path to the page module (e.g. `app/users/[id]/page.tsx`). */
  routeFile: string;
  /** Whether SSR is enabled for this route. */
  ssr: boolean;
  /** JSON array of layout file paths (relative to cwd), outermost first. */
  layoutsJson?: string | undefined;
  /** Relative path to the nearest loading.tsx (for client-side Suspense fallback). */
  loadingFile?: string | undefined;
  /** Extra content injected into <head> (used by Vite to insert HMR scripts). */
  headExtra?: string | undefined;
  /** Nonce for CSP inline scripts (optional). */
  nonce?: string | undefined;
  /**
   * Serialised `<script type="importmap">` JSON.
   * Injected before any module scripts so the browser can resolve federated
   * remote specifiers (e.g. `"RemoteApp/Button"`) via native ESM import maps.
   * Generated by `buildImportMap()` from the project's `alabjs.config.ts`.
   */
  importMapJson?: string | undefined;
  /**
   * Build ID for skew protection.
   * Injected as `<meta name="alabjs-build-id">` so the client SPA router can
   * detect a deployment change mid-session and trigger a hard reload instead
   * of swapping components in-place with mismatched JS chunks.
   */
  buildId?: string | undefined;
}

/** Build the opening HTML fragment — everything up to and including `<div id="alabjs-root">`. */
export function htmlShellBefore(opts: HtmlShellOptions): string {
  const {
    metadata,
    paramsJson,
    searchParamsJson,
    routeFile,
    ssr,
    layoutsJson,
    loadingFile,
    headExtra = "",
    buildId,
    importMapJson,
  } = opts;

  const titleTag = metadata.title
    ? `<title>${escHtml(metadata.title)}</title>`
    : "";

  const descTag = metadata.description
    ? `<meta name="description" content="${escAttr(metadata.description)}" />`
    : "";

  const canonicalTag = metadata.canonical
    ? `<link rel="canonical" href="${escAttr(metadata.canonical)}" />`
    : "";

  const robotsTag = metadata.robots
    ? `<meta name="robots" content="${escAttr(metadata.robots)}" />`
    : "";

  const themeColorTag = metadata.themeColor
    ? `<meta name="theme-color" content="${escAttr(metadata.themeColor)}" />`
    : "";

  const ogTags = metadata.og ? buildOgTags(metadata.og) : "";
  const twitterTags = metadata.twitter ? buildTwitterTags(metadata.twitter) : "";
  const extraTags = metadata.extra ? buildExtraTags(metadata.extra) : "";

  return `<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    ${titleTag}
    ${descTag}
    ${canonicalTag}
    ${robotsTag}
    ${themeColorTag}
    ${ogTags}
    ${twitterTags}
    ${extraTags}
    <meta name="alabjs-route" content="${escAttr(routeFile)}" />
    <meta name="alabjs-ssr" content="${ssr ? "true" : "false"}" />
    <meta name="alabjs-params" content="${escAttr(paramsJson)}" />
    <meta name="alabjs-search-params" content="${escAttr(searchParamsJson)}" />
    ${layoutsJson ? `<meta name="alabjs-layouts" content="${escAttr(layoutsJson)}" />` : ""}
    ${loadingFile ? `<meta name="alabjs-loading" content="${escAttr(loadingFile)}" />` : ""}
    ${buildId ? `<meta name="alabjs-build-id" content="${escAttr(buildId)}" />` : ""}
    ${importMapJson ? `<script type="importmap">${importMapJson}</script>` : ""}
    <link rel="stylesheet" href="/app/globals.css" />
    ${headExtra}
  </head>
  <body>
    <div id="alabjs-root">`;
}

/** Build the closing HTML fragment — everything after the SSR content. */
export function htmlShellAfter(opts: { nonce?: string | undefined }): string {
  const nonceAttr = opts.nonce ? ` nonce="${escAttr(opts.nonce)}"` : "";
  // The Rust compiler (oxc_transformer::enable_all) always emits $RefreshReg$ /
  // $RefreshSig$ calls into TSX files, even in production builds. These are
  // React Fast Refresh globals that only exist when the dev preamble is injected.
  // In production there is no preamble, so the calls throw ReferenceError which
  // silently aborts module loading and prevents React from mounting.
  //
  // A classic (non-module) <script> executes synchronously during HTML parsing,
  // before any <script type="module"> is evaluated (modules are always deferred).
  // Defining no-op shims here guarantees they exist before any page chunk runs.
  const refreshShim = `<script${nonceAttr}>` +
    `if(typeof $RefreshReg$==="undefined"){` +
    `window.$RefreshReg$=function(){};` +
    `window.$RefreshSig$=function(){return function(x){return x};}` +
    `}</script>`;
  return `</div>
    ${refreshShim}
    <script type="module" src="/@alabjs/client"${nonceAttr}></script>
  </body>
</html>`;
}

/**
 * Build just the alab `<meta>` tags used for client hydration.
 * Used when the page component renders a full `<html>` document so the tags
 * can be injected into the user-controlled `<head>` rather than the shell.
 */
export function buildAlabMetaTags(opts: Omit<HtmlShellOptions, "metadata" | "headExtra">): string {
  const { routeFile, ssr, paramsJson, searchParamsJson, layoutsJson, loadingFile, buildId } = opts;
  return [
    `<meta name="alabjs-route" content="${escAttr(routeFile)}" />`,
    `<meta name="alabjs-ssr" content="${ssr ? "true" : "false"}" />`,
    `<meta name="alabjs-params" content="${escAttr(paramsJson)}" />`,
    `<meta name="alabjs-search-params" content="${escAttr(searchParamsJson)}" />`,
    layoutsJson ? `<meta name="alabjs-layouts" content="${escAttr(layoutsJson)}" />` : "",
    loadingFile ? `<meta name="alabjs-loading" content="${escAttr(loadingFile)}" />` : "",
    buildId ? `<meta name="alabjs-build-id" content="${escAttr(buildId)}" />` : "",
    // Signal to the client bootstrap that it must use hydrateRoot(document, …)
    // instead of mounting into <div id="alabjs-root">.
    `<meta name="alabjs-full-document" content="true" />`,
  ].filter(Boolean).join("\n    ");
}

/**
 * Inject alab hydration meta tags and the client bootstrap script into a
 * full-document SSR string (i.e. one whose root element is `<html>`).
 *
 * The meta tags are appended before `</head>` and the client script before
 * `</body>`.  If neither marker is found the strings are appended verbatim.
 */
export function injectIntoFullDocument(
  ssrHtml: string,
  opts: Omit<HtmlShellOptions, "metadata" | "headExtra">,
): string {
  const metaTags = buildAlabMetaTags(opts);
  const nonceAttr = opts.nonce ? ` nonce="${escAttr(opts.nonce)}"` : "";
  const clientScript = `<script type="module" src="/@alabjs/client"${nonceAttr}></script>`;
  const importMapTag = opts.importMapJson
    ? `<script type="importmap">${opts.importMapJson}</script>\n  `
    : "";

  let result = ssrHtml;

  // Inject import map + meta tags before </head> (case-insensitive).
  // Import map must precede any <script type="module"> elements.
  if (/<\/head>/i.test(result)) {
    result = result.replace(/<\/head>/i, `  ${importMapTag}${metaTags}\n  </head>`);
  } else {
    result = `${importMapTag}${metaTags}\n` + result;
  }

  // Inject client bootstrap script before </body>.
  if (/<\/body>/i.test(result)) {
    result = result.replace(/<\/body>/i, `  ${clientScript}\n  </body>`);
  } else {
    result = result + "\n" + clientScript;
  }

  return result;
}

// ─── Helpers ──────────────────────────────────────────────────────────────────

function escHtml(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;");
}

function escAttr(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/"/g, "&quot;");
}

function buildOgTags(og: NonNullable<PageMetadata["og"]>): string {
  const tags: string[] = [];
  if (og.title) tags.push(`<meta property="og:title" content="${escAttr(og.title)}" />`);
  if (og.description) tags.push(`<meta property="og:description" content="${escAttr(og.description)}" />`);
  if (og.image) tags.push(`<meta property="og:image" content="${escAttr(og.image)}" />`);
  if (og.url) tags.push(`<meta property="og:url" content="${escAttr(og.url)}" />`);
  if (og.type) tags.push(`<meta property="og:type" content="${escAttr(og.type)}" />`);
  if (og.siteName) tags.push(`<meta property="og:site_name" content="${escAttr(og.siteName)}" />`);
  return tags.join("\n    ");
}

function buildTwitterTags(tw: NonNullable<PageMetadata["twitter"]>): string {
  const tags: string[] = [];
  if (tw.card) tags.push(`<meta name="twitter:card" content="${escAttr(tw.card)}" />`);
  if (tw.title) tags.push(`<meta name="twitter:title" content="${escAttr(tw.title)}" />`);
  if (tw.description) tags.push(`<meta name="twitter:description" content="${escAttr(tw.description)}" />`);
  if (tw.image) tags.push(`<meta name="twitter:image" content="${escAttr(tw.image)}" />`);
  if (tw.creator) tags.push(`<meta name="twitter:creator" content="${escAttr(tw.creator)}" />`);
  return tags.join("\n    ");
}

function buildExtraTags(extra: NonNullable<PageMetadata["extra"]>): string {
  return extra
    .map((attrs) => {
      const attrStr = Object.entries(attrs)
        .map(([k, v]) => `${k}="${escAttr(v)}"`)
        .join(" ");
      return `<meta ${attrStr} />`;
    })
    .join("\n    ");
}
